version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_MODE=paper
      - TRADING_MODE=auto
      - COINDESK_API_KEY=${COINDESK_API_KEY}
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - REDIS_URL=redis://redis:6379/0
      - STARTING_CASH_USD=10000
      - NEWS_SECONDARY=NewsAPI
      - NEWS_RECENCY_HALF_LIFE_MIN=90
      - NEWS_CREDIBILITY_TABLE=marketwatch:1.0,newsapi:0.8,gnews:0.7
      - NEWS_HALT_WINDOW_MIN=20
      - MAX_POSITION_PCT=0.2
      - DAILY_LOSS_HALT_PCT=0.02
      - SLIPPAGE_BPS=5
      - FEE_BPS=10
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
